import AppKit
import Foundation

/// Generates HTML from a StoredReport and opens it in the browser.
enum ReportExporter {

    // MARK: - Generate HTML

    static func generateHtml(from report: StoredReport) -> String {
        var html = """
        <!DOCTYPE html>
        <html>
        <head>
        <meta charset="utf-8">
        <title>\(escapeHtml(report.title))</title>
        <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #0a0a0a;
            color: #e0e0e0;
        }
        h1 { color: #4A9EFF; border-bottom: 2px solid #333; padding-bottom: 10px; }
        h2 { color: #8B5CF6; margin-top: 30px; }
        .prompt { background: #1a1a2e; padding: 15px; border-radius: 8px; margin: 15px 0; border-left: 4px solid #4A9EFF; }
        .agent-card {
            background: #1a1a2e;
            border: 1px solid #333;
            border-radius: 8px;
            margin: 15px 0;
            overflow: hidden;
        }
        .agent-header {
            background: #2a2a3a;
            padding: 12px 15px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .agent-header h3 { margin: 0; color: #e0e0e0; }
        .agent-content { padding: 15px; }
        .error { color: #FF6B6B; }
        .success { color: #4CAF50; }
        .tokens { font-size: 0.85em; color: #888; }
        code { background: #2a2a2e; padding: 2px 6px; border-radius: 3px; font-family: 'SF Mono', monospace; }
        pre { background: #2a2a2e; padding: 12px; border-radius: 6px; overflow-x: auto; }
        pre code { background: none; padding: 0; }
        .meta { font-size: 0.85em; color: #888; margin-top: 10px; }
        .timestamp { color: #666; font-size: 0.85em; }
        </style>
        </head>
        <body>
        <h1>\(escapeHtml(report.title))</h1>
        <p class="timestamp">Generated: \(formatDate(report.timestamp))</p>
        <div class="prompt"><strong>Prompt:</strong><br>\(escapeHtml(report.prompt))</div>
        """

        for result in report.results {
            let statusClass = result.error != nil ? "error" : "success"
            let statusIcon = result.error != nil ? "&#10060;" : "&#9989;"
            let name = result.agentName ?? "\(result.providerId) / \(result.model)"

            html += """
            <div class="agent-card">
            <div class="agent-header">
                <h3>\(statusIcon) \(escapeHtml(name))</h3>
                <span class="tokens">\(result.inputTokens) in / \(result.outputTokens) out</span>
            </div>
            <div class="agent-content">
            """

            if let error = result.error {
                html += "<p class=\"error\">\(escapeHtml(error))</p>"
            } else if let analysis = result.analysis {
                html += convertMarkdownToHtml(analysis)
            }

            if let citations = result.citations, !citations.isEmpty {
                html += "<div class=\"meta\"><strong>Sources:</strong><br>"
                for (i, citation) in citations.enumerated() {
                    html += "\(i + 1). \(escapeHtml(citation))<br>"
                }
                html += "</div>"
            }

            if let cost = result.apiCost {
                html += "<p class=\"meta\">Cost: $\(String(format: "%.8f", cost))</p>"
            }

            html += "</div></div>"
        }

        html += """
        <p class="meta" style="text-align: center; margin-top: 30px;">Generated by macAI</p>
        </body>
        </html>
        """

        return html
    }

    // MARK: - Save and Open

    static func saveAndOpen(html: String, title: String) {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.html]
        panel.nameFieldStringValue = "\(sanitizeFilename(title)).html"
        panel.title = "Export Report"

        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }
            do {
                try html.write(to: url, atomically: true, encoding: .utf8)
                NSWorkspace.shared.open(url)
            } catch {
                // Silently fail - user can try again
            }
        }
    }

    /// Quick export without file dialog - saves to temp and opens.
    static func quickOpen(html: String, title: String) {
        let tempDir = FileManager.default.temporaryDirectory
        let filename = "\(sanitizeFilename(title))_\(Int(Date().timeIntervalSince1970)).html"
        let fileURL = tempDir.appendingPathComponent(filename)

        do {
            try html.write(to: fileURL, atomically: true, encoding: .utf8)
            NSWorkspace.shared.open(fileURL)
        } catch {
            // Silently fail
        }
    }

    // MARK: - Helpers

    private static func escapeHtml(_ text: String) -> String {
        text.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    private static func sanitizeFilename(_ text: String) -> String {
        let invalid = CharacterSet.alphanumerics.inverted
        return text.components(separatedBy: invalid).joined(separator: "_").prefix(50).description
    }

    /// Basic markdown to HTML conversion for report export.
    private static func convertMarkdownToHtml(_ markdown: String) -> String {
        var html = escapeHtml(markdown)

        // Code blocks (``` ... ```)
        let codeBlockPattern = "```(\\w*)\\n(.*?)```"
        if let regex = try? NSRegularExpression(pattern: codeBlockPattern, options: .dotMatchesLineSeparators) {
            let range = NSRange(html.startIndex..<html.endIndex, in: html)
            html = regex.stringByReplacingMatches(in: html, range: range, withTemplate: "<pre><code>$2</code></pre>")
        }

        // Inline code (`...`)
        let inlineCodePattern = "`([^`]+)`"
        if let regex = try? NSRegularExpression(pattern: inlineCodePattern) {
            let range = NSRange(html.startIndex..<html.endIndex, in: html)
            html = regex.stringByReplacingMatches(in: html, range: range, withTemplate: "<code>$1</code>")
        }

        // Bold (**...**)
        let boldPattern = "\\*\\*(.+?)\\*\\*"
        if let regex = try? NSRegularExpression(pattern: boldPattern) {
            let range = NSRange(html.startIndex..<html.endIndex, in: html)
            html = regex.stringByReplacingMatches(in: html, range: range, withTemplate: "<strong>$1</strong>")
        }

        // Italic (*...*)
        let italicPattern = "\\*(.+?)\\*"
        if let regex = try? NSRegularExpression(pattern: italicPattern) {
            let range = NSRange(html.startIndex..<html.endIndex, in: html)
            html = regex.stringByReplacingMatches(in: html, range: range, withTemplate: "<em>$1</em>")
        }

        // Headers (### -> h3, ## -> h2, # -> h1)
        html = html.components(separatedBy: "\n").map { line in
            if line.hasPrefix("### ") { return "<h4>\(String(line.dropFirst(4)))</h4>" }
            if line.hasPrefix("## ") { return "<h3>\(String(line.dropFirst(3)))</h3>" }
            if line.hasPrefix("# ") { return "<h2>\(String(line.dropFirst(2)))</h2>" }
            return line
        }.joined(separator: "\n")

        // Line breaks
        html = html.replacingOccurrences(of: "\n\n", with: "</p><p>")
        html = "<p>" + html + "</p>"

        return html
    }
}
