using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;
using AI.Data;
using Microsoft.Win32;

namespace AI.Helpers;

public static class ReportExporter
{
    // Generate HTML

    public static string GenerateHtml(StoredReport report)
    {
        var sb = new StringBuilder();
        sb.Append($"""
            <!DOCTYPE html>
            <html>
            <head>
            <meta charset="utf-8">
            <title>{EscapeHtml(report.Title)}</title>
            <style>
            body {{
                font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, Roboto, sans-serif;
                max-width: 1200px;
                margin: 0 auto;
                padding: 20px;
                background: #0a0a0a;
                color: #e0e0e0;
            }}
            h1 {{ color: #4A9EFF; border-bottom: 2px solid #333; padding-bottom: 10px; }}
            h2 {{ color: #8B5CF6; margin-top: 30px; }}
            .prompt {{ background: #1a1a2e; padding: 15px; border-radius: 8px; margin: 15px 0; border-left: 4px solid #4A9EFF; }}
            .agent-card {{
                background: #1a1a2e;
                border: 1px solid #333;
                border-radius: 8px;
                margin: 15px 0;
                overflow: hidden;
            }}
            .agent-header {{
                background: #2a2a3a;
                padding: 12px 15px;
                display: flex;
                justify-content: space-between;
                align-items: center;
            }}
            .agent-header h3 {{ margin: 0; color: #e0e0e0; }}
            .agent-content {{ padding: 15px; }}
            .error {{ color: #FF6B6B; }}
            .success {{ color: #4CAF50; }}
            .tokens {{ font-size: 0.85em; color: #888; }}
            code {{ background: #2a2a2e; padding: 2px 6px; border-radius: 3px; font-family: 'Cascadia Code', 'Consolas', monospace; }}
            pre {{ background: #2a2a2e; padding: 12px; border-radius: 6px; overflow-x: auto; }}
            pre code {{ background: none; padding: 0; }}
            .meta {{ font-size: 0.85em; color: #888; margin-top: 10px; }}
            .timestamp {{ color: #666; font-size: 0.85em; }}
            </style>
            </head>
            <body>
            <h1>{EscapeHtml(report.Title)}</h1>
            <p class="timestamp">Generated: {report.Timestamp:yyyy-MM-dd HH:mm:ss}</p>
            <div class="prompt"><strong>Prompt:</strong><br>{EscapeHtml(report.Prompt)}</div>
            """);

        foreach (var result in report.Results)
        {
            var statusClass = result.Error != null ? "error" : "success";
            var statusIcon = result.Error != null ? "&#10060;" : "&#9989;";
            var name = result.AgentName ?? $"{result.ProviderId} / {result.Model}";

            sb.Append($"""
                <div class="agent-card">
                <div class="agent-header">
                    <h3>{statusIcon} {EscapeHtml(name)}</h3>
                    <span class="tokens">{result.InputTokens} in / {result.OutputTokens} out</span>
                </div>
                <div class="agent-content">
                """);

            if (result.Error != null)
                sb.Append($"<p class=\"error\">{EscapeHtml(result.Error)}</p>");
            else if (result.Analysis != null)
                sb.Append(ConvertMarkdownToHtml(result.Analysis));

            if (result.Citations is { Count: > 0 })
            {
                sb.Append("<div class=\"meta\"><strong>Sources:</strong><br>");
                for (var i = 0; i < result.Citations.Count; i++)
                    sb.Append($"{i + 1}. {EscapeHtml(result.Citations[i])}<br>");
                sb.Append("</div>");
            }

            if (result.ApiCost.HasValue)
                sb.Append($"<p class=\"meta\">Cost: ${result.ApiCost.Value:F8}</p>");

            sb.Append("</div></div>");
        }

        sb.Append("""
            <p class="meta" style="text-align: center; margin-top: 30px;">Generated by AI for Windows</p>
            </body>
            </html>
            """);

        return sb.ToString();
    }

    // Save and Open

    public static void SaveAndOpen(string html, string title)
    {
        var dialog = new SaveFileDialog
        {
            FileName = $"{SanitizeFilename(title)}.html",
            Filter = "HTML files (*.html)|*.html",
            DefaultExt = ".html",
            Title = "Export Report"
        };

        if (dialog.ShowDialog() == true)
        {
            File.WriteAllText(dialog.FileName, html);
            Process.Start(new ProcessStartInfo(dialog.FileName) { UseShellExecute = true });
        }
    }

    public static void QuickOpen(string html, string title)
    {
        var tempDir = Path.GetTempPath();
        var filename = $"{SanitizeFilename(title)}_{DateTimeOffset.UtcNow.ToUnixTimeSeconds()}.html";
        var filePath = Path.Combine(tempDir, filename);

        File.WriteAllText(filePath, html);
        Process.Start(new ProcessStartInfo(filePath) { UseShellExecute = true });
    }

    // Helpers

    private static string EscapeHtml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

    private static string SanitizeFilename(string text)
    {
        var sanitized = Regex.Replace(text, @"[^a-zA-Z0-9]", "_");
        return sanitized.Length > 50 ? sanitized[..50] : sanitized;
    }

    private static string ConvertMarkdownToHtml(string markdown)
    {
        var html = EscapeHtml(markdown);

        // Code blocks (``` ... ```)
        html = Regex.Replace(html, @"```\w*\n(.*?)```", "<pre><code>$1</code></pre>", RegexOptions.Singleline);

        // Inline code (`...`)
        html = Regex.Replace(html, @"`([^`]+)`", "<code>$1</code>");

        // Bold (**...**)
        html = Regex.Replace(html, @"\*\*(.+?)\*\*", "<strong>$1</strong>");

        // Italic (*...*)
        html = Regex.Replace(html, @"\*(.+?)\*", "<em>$1</em>");

        // Headers
        var lines = html.Split('\n');
        for (var i = 0; i < lines.Length; i++)
        {
            if (lines[i].StartsWith("### ")) lines[i] = $"<h4>{lines[i][4..]}</h4>";
            else if (lines[i].StartsWith("## ")) lines[i] = $"<h3>{lines[i][3..]}</h3>";
            else if (lines[i].StartsWith("# ")) lines[i] = $"<h2>{lines[i][2..]}</h2>";
        }
        html = string.Join('\n', lines);

        // Line breaks
        html = html.Replace("\n\n", "</p><p>");
        html = $"<p>{html}</p>";

        return html;
    }
}
