package com.ai.ui.navigation

import java.net.URLEncoder

object NavRoutes {
    const val AI = "ai"
    const val SETTINGS = "settings"
    const val SETTINGS_PROVIDER_EDIT = "settings_provider_edit/{providerId}"
    const val SETTINGS_AGENT_EDIT = "settings_agent_edit/{agentId}"
    const val SETTINGS_FLOCK_EDIT = "settings_flock_edit/{flockId}"
    const val SETTINGS_SWARM_EDIT = "settings_swarm_edit/{swarmId}"
    const val SETTINGS_INTERNAL_PROMPT_EDIT = "settings_internal_prompt_edit/{promptId}"
    const val SETTINGS_AGENTS = "settings_agents"
    const val SETTINGS_FLOCKS = "settings_flocks"
    const val SETTINGS_SWARMS = "settings_swarms"
    const val SETTINGS_BLOCKED_MODELS = "settings_blocked_models"
    const val SETTINGS_INACCESSIBLE_MODELS = "settings_inaccessible_models"
    const val SETTINGS_MODEL_COOLDOWNS = "settings_model_cooldowns"
    const val SETTINGS_MANUAL_MODEL_TYPES = "settings_manual_model_types"
    const val SETTINGS_INTERNAL_PROMPTS_BY_CATEGORY = "settings_internal_prompts/{category}"
    const val HELP = "help"
    const val HELP_FOR_TOPIC = "help/{topicId}"
    const val DOCUMENTATION = "documentation"
    const val DOCUMENTATION_MANUAL = "documentation_manual"
    const val ABOUT = "about"
    const val TRACE_LIST = "trace_list"
    const val TRACE_LIST_FOR_REPORT = "trace_list/{reportId}"
    const val TRACE_LIST_FOR_REPORT_CATEGORY = "trace_list/{reportId}/category/{category}"
    const val TRACE_LIST_FOR_MODEL = "trace_list_for_model/{provider}/{model}"
    const val TRACE_LIST_FOR_RUN = "trace_list_for_run/{runId}"
    const val TRACE_DETAIL = "trace_detail/{filename}"
    const val AI_HISTORY = "ai_history"
    const val AI_REPORTS_HUB = "ai_reports_hub"
    /** Wrapper screen with three tap-through rows that previously
     *  lived in the Reports hub's "Start" card. Routes to
     *  [AI_NEW_REPORT] for the actual form screen. */
    const val AI_NEW_REPORT_HUB = "ai_new_report_hub"
    const val AI_NEW_REPORT = "ai_new_report"
    const val AI_NEW_REPORT_WITH_PARAMS = "ai_new_report/{title}/{prompt}"
    const val AI_PROMPT_HISTORY = "ai_prompt_history"
    const val AI_EXAMPLE_PROMPT_PICKER = "ai_example_prompt_picker"
    /** Pattern carries an optional `initialView` query-param consumed
     *  by the AI_REPORTS composable. Existing call sites navigate with
     *  the bare string ("ai_reports"); the per-row 👁 View icon uses
     *  [aiReportView] which appends `?initialView=true` so the
     *  destination seeds [ReportsScreenNav]'s View tile-grid overlay
     *  on first composition. */
    const val AI_REPORTS = "ai_reports?initialView={initialView}"
    /** Helper for the row-level 🔧 Manage icon — same destination
     *  the existing navigation uses. */
    fun aiReportManage() = "ai_reports"
    /** Helper for the row-level 👁 View icon — seeds the View
     *  tile grid (`showViewReportScreen`) on first composition only. */
    fun aiReportView() = "ai_reports?initialView=true"
    const val AI_SEARCH = "ai_search"
    const val AI_LOCAL_SEARCH = "ai_local_search"
    const val AI_QUICK_LOCAL_SEARCH = "ai_quick_local_search"
    const val AI_REPORT_MANAGE = "ai_report_manage"
    const val AI_CHAT_MANAGE = "ai_chat_manage"
    const val AI_KNOWLEDGE = "ai_knowledge"
    const val AI_KNOWLEDGE_NEW = "ai_knowledge_new"
    const val AI_KNOWLEDGE_DETAIL = "ai_knowledge_detail/{kbId}"
    const val AI_LOCAL_SEMANTIC_SEARCH = "ai_local_semantic_search"
    const val AI_USAGE = "ai_usage"
    const val AI_COST_CONFIG = "ai_cost_config"
    const val AI_SETUP = "ai_setup"
    const val AI_HOUSEKEEPING = "ai_housekeeping"
    const val AI_BACKUP_RESTORE = "ai_backup_restore"
    const val AI_IMPORT_EXPORT = "ai_import_export"
    const val AI_TRIM_BY_AGE = "ai_trim_by_age"
    const val AI_UPDATE_FROM_CLOUD = "ai_update_from_cloud"
    const val AI_RESET = "ai_reset"
    const val AI_RESET_RUNTIME = "ai_reset_runtime"
    const val AI_RESET_INFO_PROVIDERS = "ai_reset_info_providers"
    const val AI_RESET_CONFIGURATION = "ai_reset_configuration"
    const val AI_RESET_ASSETS = "ai_reset_assets"
    const val AI_RESET_APPLICATION = "ai_reset_application"
    const val AI_REFRESH = "ai_refresh"
    const val AI_TEST = "ai_test"
    const val AI_TEST_ALL_MODELS = "ai_test_all_models"
    const val AI_APPLOG_LIST = "ai_applog_list"
    const val AI_APPLOG_DETAIL = "ai_applog_detail/{filename}?search={search}"
    const val AI_CHATS_HUB = "ai_chats_hub"
    const val AI_CHAT_AGENT_SELECT = "ai_chat_agent_select"
    const val AI_CHAT_WITH_AGENT = "ai_chat_with_agent/{agentId}"
    const val AI_CHAT_SEARCH = "ai_chat_search"
    const val AI_CHAT_PROVIDER = "ai_chat_provider"
    const val AI_CHAT_PARAMS = "ai_chat_params/{provider}/{model}"
    const val AI_CHAT_SESSION = "ai_chat_session/{provider}/{model}"
    const val AI_CHAT_HISTORY = "ai_chat_history"
    const val AI_CHAT_CONTINUE = "ai_chat_continue/{sessionId}"
    const val AI_MODEL_SEARCH = "ai_model_search"
    const val AI_MODEL_INFO = "ai_model_info/{provider}/{model}"
    const val AI_MANUAL_OVERRIDE_ADD = "ai_manual_override_add/{provider}/{model}"
    const val AI_MANUAL_COST_OVERRIDE_ADD = "ai_manual_cost_override_add/{provider}/{model}"
    const val AI_API_TEST = "ai_api_test"
    const val AI_API_TEST_EDIT = "ai_api_test_edit"
    const val AI_DUAL_CHAT_SETUP = "ai_dual_chat_setup"
    const val AI_DUAL_CHAT_SESSION = "ai_dual_chat_session"
    const val DEVELOPER_OPTIONS = "developer_options"

    private fun encode(s: String) = URLEncoder.encode(s, "UTF-8").replace("+", "%20")

    fun traceDetail(filename: String) = "trace_detail/$filename"
    fun aiAppLogDetail(filename: String, search: String = "") =
        "ai_applog_detail/$filename?search=${encode(search)}"
    fun traceListForReport(reportId: String) = "trace_list/$reportId"
    fun traceListForReportCategory(reportId: String, category: String) =
        "trace_list/$reportId/category/${encode(category)}"
    fun settingsProviderEdit(providerId: String) = "settings_provider_edit/$providerId"
    fun settingsAgentEdit(agentId: String) = "settings_agent_edit/$agentId"
    fun settingsFlockEdit(flockId: String) = "settings_flock_edit/$flockId"
    fun settingsSwarmEdit(swarmId: String) = "settings_swarm_edit/$swarmId"
    fun settingsInternalPromptEdit(promptId: String) = "settings_internal_prompt_edit/$promptId"
    fun settingsInternalPromptsByCategory(category: String) = "settings_internal_prompts/${encode(category)}"
    fun traceListForModel(provider: String, model: String) = "trace_list_for_model/$provider/${encode(model)}"
    fun traceListForRun(runId: String) = "trace_list_for_run/${encode(runId)}"
    fun aiModelInfo(provider: String, model: String) = "ai_model_info/$provider/${encode(model)}"
    fun aiManualOverrideAdd(provider: String, model: String) = "ai_manual_override_add/$provider/${encode(model)}"
    fun aiManualCostOverrideAdd(provider: String, model: String) = "ai_manual_cost_override_add/$provider/${encode(model)}"
    fun aiChatContinue(sessionId: String) = "ai_chat_continue/$sessionId"
    fun aiKnowledgeDetail(kbId: String) = "ai_knowledge_detail/$kbId"
    fun aiChatWithAgent(agentId: String) = "ai_chat_with_agent/$agentId"
    fun aiChatParams(provider: String, model: String) = "ai_chat_params/$provider/${encode(model)}"
    fun aiChatSession(provider: String, model: String) = "ai_chat_session/$provider/${encode(model)}"
    fun aiNewReportWithParams(title: String, prompt: String) = "ai_new_report/${encode(title)}/${encode(prompt)}"
    fun helpForTopic(topicId: String) = "help/${encode(topicId)}"
}
