package com.ai.ui.admin

internal val glossaryHelp: Map<String, HelpContent> = mapOf(
    "about" to HelpContent(
        title = "Help - About",
        cards = listOf(
            HelpCard("Overview", "Lightweight hub reached from the home screen's About card (or the bottom-bar app icon). Shows the AI logo, the installed version, the build date stamped into the APK at compile time, and a link to the GitHub source. Two cards underneath route to the bundled documentation: the end-user Manual and the developer Technical documentation."),
            HelpCard("Version + build + install times", "`Version <X.Y.Z>` is the `versionName` from the manifest (set in `ai/build.gradle`). `Built <stamp>` is read from the bundled `assets/build-timestamp.txt`, written on every Gradle build by the never-up-to-date `generateBuildStamp` task — always matches the moment the APK was produced (sidesteps the configuration-cache trap that made the old `BuildConfig.BUILD_TIMESTAMP` go stale). `Installed <stamp>` is `PackageInfo.lastUpdateTime` — the moment the APK was last written to the device. Both surface so you can tell the difference between 'old build still installed' and 'fresh install of a fresh build'."),
            HelpCard("GitHub link", "Opens `github.com/herbert256/ai` in the system browser. Public mirror of the source tree."),
            HelpCard("Manual card", "Opens the end-user Manual — a per-screen walkthrough of every feature, bundled at `assets/docs/manual/`."),
            HelpCard("Technical documentation card", "Opens the developer Technical documentation — architecture / data structures / build process / etc., bundled at `assets/docs/technical/`."),
            HelpCard("Copyright + licence", "GPL v2.0 — the LICENSE file at the repo root has the full text. Two footer lines pinned at the bottom of the page so the licence stays in front of every user."),
            HelpCard("Pitfalls", "The build timestamp moves on every assemble even for unchanged code (gradle stamps unconditionally). Use it for 'is the running APK the one I just built?' checks, not for change detection.")
        )
    ),
    "manual" to HelpContent(
        title = "Help - Manual",
        cards = listOf(
            HelpCard("Overview", "End-user walkthrough of every screen and feature, bundled in the APK at `assets/docs/manual/`. Mirrors what a printed quick-start would cover: how to send a report, what each screen does, where the controls live. Sibling hub to the Technical documentation for developer-oriented reference. No network — every page is read from disk."),
            HelpCard("Index", "The first page is a card-style table of contents grouped by use case (Getting started, Reports, Chat, Translation, Settings, etc.). Pages target users, not developers; concrete control names and label quotes match what's on-screen."),
            HelpCard("Navigation", "Tap a card on the index to open that page. The top \"Jump to\" panel anchor-links to each section inside a long page. The system back button walks the browser history first, then exits."),
            HelpCard("Authoritative source", "Hand-written; the code is the ultimate source of truth. When a screen and the manual disagree, the screen wins — open the page's underlying `.md` in the repo to file a fix."),
            HelpCard("Pitfalls", "Pages still marked \"Pass 1 stub\" are placeholders pending a rewrite pass — they link back to the original `doc/<name>.md`. JavaScript is disabled in this WebView; only static HTML + CSS renders.")
        )
    ),
    "technical_documentation" to HelpContent(
        title = "Help - Technical documentation",
        cards = listOf(
            HelpCard("Overview", "Developer-oriented hub over the project's technical documentation, bundled in the APK at `assets/docs/technical/`. Mobile-friendly rewrite of the `doc/` markdown tree: collapsible cards instead of wide tables, nested HTML trees instead of ASCII diagrams, dark theme matching the app. Sibling hub to the end-user Manual. No network — every page is read from disk."),
            HelpCard("Index", "The first page is a card-style table of contents. Sections: For developers (Architecture, Development, API formats, Data structures, Secondary results, Model test, Cooldowns, Help system, AppLog, Report icons, Throttle), Subsystem deep dives (Translation, Share target, Backup & restore), Reference data (Providers, Repositories, Persistent state), Backlog (TODO)."),
            HelpCard("Navigation", "Tap a card on the index to open that doc. Inside a page, the top \"Jump to\" panel anchor-links to each section. Long reference sections (per data class, per provider) are collapsed by default — tap to expand. The system back button walks the browser history first, then exits the screen."),
            HelpCard("Authoritative source", "Documentation is hand-written; the code is the ultimate source of truth. The bundled HTML is a snapshot — when in doubt, the file pointers at the bottom of `index` lead back to the live source files."),
            HelpCard("Pitfalls", "Pages still marked \"Pass 1 stub\" are placeholders pending the second rewrite pass — they link back to the original `doc/<name>.md` in the repo. JavaScript is disabled in this WebView; only static HTML + CSS renders.")
        )
    ),
    "help_home_icons" to HelpContent(
        title = "Help - Icons",
        cards = listOf(
            HelpCard("Overview", "Legend for every icon you'll see in the app's title bars, action rows and lists. The table below pairs each glyph with what it does and where it shows up. Reached from the Help home → \"Help - Icons\" link.")
        )
    ),
    "help_home_info_providers" to HelpContent(
        title = "Help - Info providers",
        cards = listOf(
            HelpCard("Overview", "External services the app fetches metadata from — model lists, pricing tiers, capability flags, free / spot pools. Tap a row in the table below to drill into that one provider's detail topic (where it's read, when it refreshes, fallback chain, …). Reached from the Help home → \"Help - Info providers\" link.")
        )
    ),
    "help_home_ai_providers" to HelpContent(
        title = "Help - AI providers (cloud)",
        cards = listOf(
            HelpCard("Overview", "Every cloud LLM / embedder / reranker provider the app can talk to. Tap a row in the table below for that provider's setup notes — endpoint, auth shape, model-list freshness, anything that's worth knowing before pasting an API key. Reached from the Help home → \"Help - AI providers\" link.")
        )
    ),
    "concepts" to HelpContent(
        title = "Help - How it works",
        cards = listOf(
            HelpCard("What this page is", "Behaviours that span multiple screens. The per-screen ❓ help covers buttons / cards / fields on one screen; this page collects the things that quietly happen across the whole app — background sweeps, auto-reconcile, retry policy. Reach it from any per-screen help page's footer (\"How it works\") or from the Help home."),
            HelpCard("Stalled translation auto-reconcile", "Live translation rows (⏳ + 'done / total') auto-heal when their in-memory state has drifted from disk. Two triggers: (a) every report-open, the resume pass scans for any in-memory run flagged in-flight with no live dispatch job — those are demonstrably stuck (a cross-translate / restart-failed coroutine died before flipping the finished flag) and get rebuilt immediately; (b) a 10-second sanity poll on the result page catches rows where the done count already equals total but the row is still flagged in-flight. Either trigger silently rebuilds the in-memory state from the persisted SecondaryResult rows. The hourglass clears, the per-status counts on the run drill-in turn truthful, and any placeholder rows the rebuild surfaces show as Queue so you can decide whether to Restart them."),
            HelpCard("App-wide background resume sweep", "Once on app start and then every 30 seconds the app runs the same per-report stale-runs resume across every report modified in the last 7 days — translation placeholders that never converged, fan-out pairs the previous session abandoned, single-Meta calls left in PENDING. You don't have to open each report individually for its dropped work to come back. Logs land under the BgResumeSweep tag. Reports older than 7 days are skipped (out of the active-work window); a kill+restart catches them on next open."),
            HelpCard("429 / 529 handling", "Translation runs with ≤ 3 models retry rate-limited (429) or overloaded (529) calls inline on the same model up to 3 times (1 s backoff each, configurable in Settings → Network). Runs with > 3 models skip the inline retry: a 429 / 529 finalises immediately as a Failed attempt and the item is requeued for a different model — the cross-model bounce is faster than sleeping on the same one when alternatives are available. Long Retry-After (> 1 h) still benches the model on ModelCooldownStore either way."),
            HelpCard("Cost-aware hesitation (Speed / Mixed / Cost)", "In a multi-model translation run each worker hesitates before pulling its next item, proportional to how much pricier its model is than the cheapest. Cost mode (default) is the full bias — the cheapest model drains the queue first, expensive ones only pick up what the cheap ones can't keep up with. Mixed softens the bias (caps at 5 s). Speed disables hesitation entirely — every model pulls as fast as its per-host caps allow. Toggle is on the Translation L1 screen, switchable mid-run; the worker re-reads the mode before every pull so a change takes effect within ~1 s."),
            HelpCard("Translation mode persistence", "The Speed / Mixed / Cost choice is saved per-runId in SharedPreferences (TranslationModeStore). A process kill / app restart resumes the run in the same mode. Deleting the run clears the entry so prefs don't leak.")
        )
    ),
    "help_about" to HelpContent(
        title = "Help - About the app",
        cards = listOf(
            HelpCard("What this app is", "A multi-provider AI client for Android. The headline feature is the Report flow: one prompt fired at many models in parallel, every response rendered side-by-side, with token/cost stats per row and post-hoc operations (rerank, compare, translate, moderate, fan-out) you can run over the completed results. There's also a one-model Chat flow for follow-up exchanges."),
            HelpCard("Who it's for", "Power users who want to compare what different models do with the same prompt, batch-process prompts at scale, or build their own meta-workflows on top of multi-model output. The app is opinionated towards the Report flow — it's the centre of gravity. If you only want a single-model ChatGPT-style conversation, this app is over-spec'd for that."),
            HelpCard("Multi-model Reports", "Pick a Flock, Swarm, or ad-hoc set of agents, paste a prompt, fire. Each agent's call runs in parallel up to the per-host throttle gates; results stream into the result page as they arrive. The completed Report is one JSON file on disk that survives app restarts, can be exported (HTML / PDF / DOCX / ODT / JSON traces), and is the input to every Meta operation."),
            HelpCard("Meta operations", "After a Report finishes, you can chain operations over its results: Rerank (order by relevance / quality), Compare / Summarize / Critique (any user-defined chat-type meta prompt; cross-result synthesis), Moderate (per-row safety scoring), Translate (multi-language render), and Fan-out (run a chat meta against every pair of source results). Outputs persist alongside the Report so you can revisit them later."),
            HelpCard("Architecture at a glance", "Single Activity, Jetpack Compose UI, Kotlin coroutines for concurrency, Retrofit + OkHttp + custom interceptors for the network, plain JSON files on disk for persistence (no SQLite, no Room). Every cloud provider is hit through one of three API formats (OpenAI-compatible, Anthropic, Google) so adding a provider is mostly registration, not code. The app log + per-call API tracer help you debug behaviour."),
            HelpCard("Privacy stance", "Local-first by default. Your data lives on this device under the app's private storage; uninstalling removes it. The only network traffic is the API calls you explicitly trigger to the providers you configured. No telemetry, no analytics, no \"phone home\". See Help - Privacy & data for the full inventory."),
            HelpCard("Open source + cost", "Source on GitHub (link from the About screen on Home). Licensed GPLv2. The app itself is free; you pay only for the API calls your configured providers bill you for."),
            HelpCard("Where to start", "Help - Getting started has the step-by-step. Short version: Settings → AI Setup → Providers (paste at least one API key) → Housekeeping → Refresh → Refresh all (verify keys + fetch model lists) → Hub → AI Reports → New report.")
        )
    ),
    "help_getting_started" to HelpContent(
        title = "Help - Getting started",
        cards = listOf(
            HelpCard("Step 1 — Add an API key", "Settings → AI Setup → Providers → pick a provider you have an account with (OpenAI / Anthropic / Google / OpenRouter are good starting points) → paste the key in the API Key card. The key stays on this device; it's only ever sent in the Authorization header to that one provider. Per-screen ❓ on the API Key card explains the key format."),
            HelpCard("Step 2 — Verify + fetch model lists", "Housekeeping → Refresh → Refresh all. This pings each configured provider to confirm the key works, then fetches their model catalog. Successful providers turn green; bad keys / wrong endpoints turn red with the error inline. You only need to refresh when you change providers or want to pick up newly-released models."),
            HelpCard("Step 3 — Create an Agent (optional but recommended)", "Settings → Agents → + Agent → name it, pick a provider + model, optionally a parameter set + system prompt. An Agent is the saved combination the rest of the app composes — Reports / Chats / Flocks all dispatch named Agents rather than raw (provider, model) pairs. Quick agents for the providers you just added let you stop picking from scratch every time."),
            HelpCard("Step 4 — Fire your first Report", "Hub → AI Reports → +Agent / +Flock / +Swarm / +Model picks the model set; type a prompt below; Generate. The result page populates as each model returns. Subject row shows the running cost in cents. Once every row has settled, the action row exposes View / Edit / Regenerate / Export / Translate / Meta / Fan out."),
            HelpCard("Step 5 — Try a Meta operation", "On a finished Report, Action row → Meta → pick a meta prompt (Rerank / Summarize / Compare / your own). The meta call runs over the Report's results and lands as a new card on the result page. Rerank produces a sorted table, chat metas produce a single synthesis card. Same Report can carry multiple meta runs side by side."),
            HelpCard("Step 6 — Translate the Report", "Action row → Translate → pick target languages and the model(s) to use. Multi-model translations parallelise the work and use the Speed / Mixed / Cost mode toggle to bias which model picks up what. See Help - Translations & multi-language for the workflow's specifics."),
            HelpCard("Common first-week pitfalls", "(1) Forgetting Refresh after adding a key → model lists empty. (2) Picking a tiny model for a long prompt → output truncates. (3) Hitting a 429 burst with a slow retry budget → bump Settings → Network → Max calls / minute for that provider. (4) Big translation runs feeling slow → the Cost mode hesitation is biasing toward cheaper models; flip the L1 toggle to Speed."),
            HelpCard("Help anywhere", "Every screen has its own ❓ icon in the title bar — opens the help page for that screen specifically. The Help home (this section's parent) collects cross-cutting topics; the search box at the top searches across everything.")
        )
    ),
    "help_glossary" to HelpContent(
        title = "Help - Concepts & glossary",
        cards = listOf(
            HelpCard("Overview", "The app's domain vocabulary, grouped into three buckets. Tap a category below; each lists the terms it covers with a one-paragraph explainer for each."),
            HelpCard("How the three buckets relate", "Building blocks are the atoms — Provider, Model, Agent. Groupings (Flock, Swarm) bundle Agents for one launch. Operations (Report, Chat, Meta, Fan-out, …) are the things you fire those agents at."),
            HelpCard("Why these names matter", "The UI uses the vocabulary literally. Settings → Agents edits Agents; Settings → Flocks bundles them; the Report result page lists Agent rows; the Meta picker chooses meta prompts. If a term feels alien, finding its glossary entry usually clears up whatever screen confused you.")
        )
    ),
    "help_glossary_blocks" to HelpContent(
        title = "Help - Concepts: Building blocks",
        cards = listOf(
            HelpCard("Provider", "A vendor with an endpoint the app can talk to — OpenAI, Anthropic, Google, Mistral, Cohere, OpenRouter, …. 39+ cloud providers ship with the app; you can also add custom providers via Settings → AI Setup → Providers → +Provider. Each Provider carries its API key, base URL, throttle caps (requests/min + concurrent), retry policy (429/529 budget + backoff), and the discovered model catalog."),
            HelpCard("Model", "A specific weight / size at one provider — gpt-5-mini, claude-haiku-4-5, gemini-2.5-flash, qwen-2.5-7b-instruct, etc. Reachable by id under one Provider. Pricing per million input/output tokens, capability flags (vision, web search, reasoning), and context-length attach to the Model, not the Provider. The same model id at two different providers (OpenAI gpt-4o-mini vs OpenRouter openai/gpt-4o-mini) is two separate Models."),
            HelpCard("Agent", "A saved combination of (provider, model, parameter set, optional system prompt). The atomic unit the rest of the app composes — Reports / Chats / Flocks / Swarms all dispatch Agents, never raw (provider, model) pairs. Settings → Agents edits the list. Naming Agents (\"Fast Sonnet\", \"Cheap o4-mini\") lets you pick a row by purpose rather than re-configuring each time."),
            HelpCard("Why Agent over raw pair", "Two reasons. (1) Parameter sets matter — a model called with temperature 0.2 + a strict system prompt behaves very differently from the same model with temperature 1.4 + no system prompt. The Agent freezes both. (2) When you change a model's parameters in one Agent, every Report that referenced it picks up the new behaviour on the next run — central knob, not a hundred per-Report tweaks.")
        )
    ),
    "help_glossary_groupings" to HelpContent(
        title = "Help - Concepts: Groupings",
        cards = listOf(
            HelpCard("Flock", "An ordered list of Agents you launch together as a unit. A Flock of 5 agents fired at a single prompt gives 5 parallel responses, one per Agent's configured (provider, model, parameters). Useful when you've curated a regular comparison group — \"my top 3 reasoning models\" or \"the cheap-and-fast trio\". Settings → Flocks edits the list."),
            HelpCard("Swarm", "A set of (provider, model) tuples that gets expanded into ad-hoc Agents at run time. Each tuple becomes a one-off Agent with default parameters. Useful when you want to spray a prompt at every available model from a provider, or a custom subset, without saving each as a named Agent first. Settings → Swarms edits the list."),
            HelpCard("Flock vs Swarm — when to use which", "Flock = saved Agents. Use when each Agent's parameter set / system prompt matters. Swarm = saved (provider, model) tuples. Use for breadth-first exploration — \"what does every OpenRouter Llama variant say to this prompt\" — where you don't care about per-model tuning. You can mix: a Flock of 3 hand-tuned Agents plus a Swarm dropped in via +Swarm on the new Report screen."),
            HelpCard("Practical limits", "Both are bounded by your throttle caps. A Swarm of 30 models all on the same host saturates the per-host concurrent gate; the runner will serialise them. For broad comparisons, mix providers so the per-host cap isn't the bottleneck.")
        )
    ),
    "help_glossary_operations" to HelpContent(
        title = "Help - Concepts: Operations",
        cards = listOf(
            HelpCard("Report", "The headline operation: one prompt, N models, every response rendered side-by-side. Each Report stores its prompt, the model list, every per-model response with token / cost stats, plus any meta-prompt outputs run against those responses. Lives on disk as one JSON file under <filesDir>/reports/. Survives restarts; doesn't expire; appears in History, on the result-page navigation, and in the Pin / Hub recent-reports surfaces."),
            HelpCard("Chat", "A two-way conversation with a single model. Lighter than a Report — no fan-out, no per-row comparison, no meta operations. The chat history lives on disk separately under <filesDir>/chats/. Useful for follow-up exchanges (\"now refactor that to use a sealed class\"). Reports stash an entry-point into Chat: the title bar's 💬 icon on a finished Report copies its prompt + a chosen response and launches a fresh chat."),
            HelpCard("Meta prompt", "A stored prompt template you apply to a Report's results. Built-in kinds: Rerank (order rows), Summarize / Compare / Critique etc. (chat-type meta prompt that consumes all results and produces one text output), Moderate (per-row safety scoring), Translate (per-row language render). User-defined chat meta prompts edit-able at Settings → Internal prompts. Outputs persist as SecondaryResult rows on the Report; revisitable later."),
            HelpCard("Fan-out", "Run a chat meta prompt against every pair (or curated subset of pairs) of source agents. Produces N×M responses where each pair is one cell. Useful for cross-agent comparisons — \"how does Claude critique GPT's answer\" gives 1 cell per (Claude-as-evaluator, GPT-as-source) pair. Lives in the same SecondaryResult table; the Fan-out drill-in (L1/L2/L3) lets you inspect cells individually, restart failed ones, generate per-cell icons."),
            HelpCard("Rerank", "A meta operation that asks a model to assign a rank to each Report row, optionally with rationale. Output is a structured table — each cell carries an anchor link back to the agent card it scored, so tapping a Rerank row jumps to the original response. Useful for picking \"which of these 8 answers is best\"."),
            HelpCard("Moderation", "Per-row content safety scoring against a provider's moderation endpoint (OpenAI / Mistral). Returns per-row category flags + scores. Useful for batch-screening generated text before pasting into a downstream system; also useful for self-audit if you're testing model outputs on contentious prompts."),
            HelpCard("Translation", "Translates a Report's title + prompt + every successful agent response + every chat-type meta result into one or more target languages. Multi-model translation runs use the Speed / Mixed / Cost mode toggle on the L1 — see Help - How it works for the hesitation mechanics. Translations live as TRANSLATE-kind SecondaryResult rows alongside the original; the language picker on the result viewer toggles which language renders."),
            HelpCard("Operation composition", "Operations chain. A Report's results feed Meta operations; a Translation's per-language renders include any Meta results too; Fan-out can target the products of an earlier Meta. The Report is the root; everything else hangs off it.")
        )
    ),
    "help_costs" to HelpContent(
        title = "Help - Costs & pricing",
        cards = listOf(
            HelpCard("How pricing is attributed", "Every API call carries token counts in its response. The app multiplies those by the (input, output) per-million-token prices of the (provider, model) pair and stores the USD cost on the call's record. The result-page subject row, the per-Report cost table, the Usage screen aggregates, the export bundles' cost tables, and the per-call trace files all read from the same persisted cost numbers — they don't recompute."),
            HelpCard("Pricing tier chain", "When the app needs to look up prices for a (provider, model) pair it walks a chain of sources in order: provider self-report (OpenRouter / Together when caller is them) → manual override → LiteLLM → models.dev → llm-prices → Artificial Analysis → OpenRouter cross-provider fallback → Helicone → DEFAULT (a low-cost placeholder so totals never NaN). The first hit wins. Sources are refreshed at user-controlled intervals; the cache survives restarts."),
            HelpCard("Manual overrides take precedence", "Settings → AI Setup → Cost overrides → Add manual override. A manual override for a (provider, model) pair is consulted BEFORE the curated tiers — useful when an info-provider's catalogue is stale or wrong, when you've negotiated custom pricing, or when a brand-new model isn't in the public catalogs yet. Persisted in SharedPreferences and consulted on every cost lookup."),
            HelpCard("Where costs surface in the UI", "(1) Result-page subject row — running 💰 + cents for the open Report. (2) Per-Report cost table on the Manage screen — every call grouped by type / model / agent / language. (3) Per-call trace file — opening 🐞 from any cell shows that call's cost inline. (4) Usage screen — global aggregates across every Report on the device. (5) Export bundles — the same per-Report cost table in HTML / PDF / DOCX / ODT. (6) Translation L1 — total + per-model cost as the run progresses."),
            HelpCard("Cost-aware translation mode", "Multi-model translation runs apply a cost-aware hesitation — cheaper models pull items first, expensive ones wait proportional to their price ratio. The L1 Speed / Mixed / Cost toggle controls how aggressive that bias is. Saved per-runId across restarts. See Help - How it works for the exact formula."),
            HelpCard("Audit trail", "Every API call leaves an entry in the per-Report cost table — even failed / errored / timed-out calls. The Usage screen aggregates across every Report so you can answer \"how much have I spent this month on OpenAI?\" or \"which model produces the most spend per useful output?\". Filterable by date range and provider."),
            HelpCard("Currency + decimals", "Everything is USD, rendered as cents with two decimals (e.g. \"3.42¢\"). Fractions below 0.01¢ round to 0 in displays but the underlying number on the call record is full-precision so totals don't drift from rounding."),
            HelpCard("Spend visibility before you commit", "The action-row Generate button shows the model count it will fire. For Fan-out and Translate, the confirmation dialogs show the call count before you commit so a 4-model × 200-row translation doesn't surprise you with 800 calls. Manual sanity check: bigger than expected? Hit Cancel.")
        )
    ),
    "help_privacy" to HelpContent(
        title = "Help - Privacy & data",
        cards = listOf(
            HelpCard("Local-first principle", "Everything the app generates — Reports, Chats, traces, logs, settings, agent definitions — lives on this device only, under the app's private storage (<filesDir>/). No cloud sync, no account, no \"login with Google\". The only way data leaves the device is via API calls you trigger or a Backup zip you explicitly export."),
            HelpCard("What leaves the device", "API requests to the providers you've configured. They see your prompts and produce your responses; their privacy policy applies to that data. The info-providers (HuggingFace / models.dev / llm-prices / etc.) see model id queries when you refresh model lists or fetch pricing — no prompts, no responses, just \"what does gpt-5-mini cost\". That's the complete network surface."),
            HelpCard("API key handling", "Your API keys are stored under SharedPreferences on this device. They're sent only in the Authorization header (or query param for Google) to the matching provider. They never go anywhere else — not to the developer, not to a backend, not even to other configured providers. Switching apps doesn't expose them; uninstalling deletes them."),
            HelpCard("Telemetry — none", "No crash reporting, no analytics SDK, no \"phone home\". The app does no network beyond what you explicitly trigger. You can verify this by capturing traffic from the device or by leaving it offline and watching nothing happen."),
            HelpCard("Logs and traces", "App log + per-call API traces are stored on disk under <filesDir>/logs/ and <filesDir>/traces/. Useful for debugging — \"why did that call fail\" usually has an answer in the trace bundle. They never leave the device unless you explicitly share / export a trace (the 🐞 icon on any cell). Logs are recycled when they outgrow size limits; you can wipe them from Housekeeping."),
            HelpCard("Data wipe paths", "(1) Per-Report — long-press a row in History or use the Delete action on the result page. (2) Per-Chat — long-press in the Chats list. (3) Per-API-key — Settings → AI Setup → Providers → tap Provider → clear the key. (4) Everything — Housekeeping → Reset → \"Wipe app data\" (irreversible, recreates a fresh install state). (5) Uninstall the app — Android's sandbox guarantees <filesDir>/ is removed."),
            HelpCard("Backup file = the only off-device copy", "A Backup zip you create (Housekeeping → Backup) is the only artefact that exists outside this device — and only if you choose to share / save it. Treat the file as you'd treat your API keys: it contains them. If you upload it to a cloud you don't control, you've moved trust to that cloud."),
            HelpCard("Sandbox guarantees", "Android's per-app sandbox means no other app on this device can read <filesDir>/. The app uses MODE_PRIVATE for every SharedPreferences file. Even on a rooted device the app's files require root + a UID match to read."),
            HelpCard("Pitfalls", "Sharing a Backup zip via a non-private channel (public Drive folder, email forwarded) exposes API keys + every Report. If you do need to share data with someone, export the specific Report's HTML / PDF instead — those don't include keys.")
        )
    ),
    "help_backup" to HelpContent(
        title = "Help - Backup & restore",
        cards = listOf(
            HelpCard("What's in a backup", "Every saved Report (the JSON files under reports/) + every SecondaryResult row (under secondary/) + every captured API trace (under traces/) + every prompt / agent / system prompt / parameter set / flock / swarm / cost override (the AI settings file) + general app settings + the ModelCooldownStore (rate-limit-bench state) + the PromptCache (recently used prompts) + the InternalPromptIconCache (rendered emoji icons). One zip; fixed layout."),
            HelpCard("Backup flow", "Housekeeping → Backup → Backup all. The app composes the zip in <filesDir>/backups/ (atomic temp-file + rename so a mid-write crash doesn't leave a half-zip), then hands the resulting file URI to the Android share sheet. From the share sheet pick where it goes — Drive, email, Files, local storage, your call. The zip survives between sessions in <filesDir>/backups/ until you delete it; the app doesn't auto-clean."),
            HelpCard("Restore flow", "Housekeeping → Backup → Restore from file → pick the zip via the system file picker. The app first validates the zip's contents end-to-end before touching disk — wrong layout / unknown version / corrupt entries refuse the restore with an inline error and nothing changes. On successful validation it clears the relevant <filesDir>/ subtrees, writes every entry back atomically, and then asks you to restart the app so the in-memory caches re-read from disk."),
            HelpCard("Version compatibility", "Backups carry an export version stamped in the zip's manifest. The app currently writes version 24 and accepts restore from versions 11..24. Restoring a newer-version zip into an older app is refused (we don't know what fields a newer schema introduced). Restoring an older zip into a newer app applies any migrations the app knows about — typically adding default values for fields that didn't exist when the zip was written."),
            HelpCard("Pitfalls", "(1) Don't restore while a translation / fan-out is in flight — the running coroutines will write to disk under the about-to-be-cleared subtree. Force-stop first, then restore. (2) Restoring resets the cooldown store — any benched models become \"available\" again until they get a fresh 429. (3) The cost overrides come along with the backup; if you restore on a different device, your custom prices follow."),
            HelpCard("Migration semantics", "When the restore picks up an older zip the migration runs once during the unpack. Fields the new code added but the zip lacks get defaulted. Fields the new code removed are dropped silently. Fields renamed across versions are mapped explicitly in the migration table. doc/backup-restore.md has the version-by-version notes."),
            HelpCard("Verifying a backup", "Quick smoke test: after a backup, install a fresh copy of the app on a second device, restore the zip there, confirm the History list looks identical. The export version field at the bottom of the Backup dialog also tells you which schema you just wrote.")
        )
    ),
    "help_translations" to HelpContent(
        title = "Help - Translations & multi-language",
        cards = listOf(
            HelpCard("What gets translated", "Title + prompt + every successful agent response + every chat-type meta result on the Report. Reranks, moderations, fan-out structured outputs and the cost table aren't translated — they're structured data, not narrative text. The original Report stays untouched; translations live as TRANSLATE-kind SecondaryResult rows alongside everything else and surface via the language picker on the result viewer."),
            HelpCard("Picking a target language", "Action row → Translate → language picker. Built-in list covers 30+ languages; the picker also accepts custom languages typed in. Multiple languages per launch are supported — a single Translate fires N×items parallel work, one stream per target language."),
            HelpCard("Single- vs multi-model", "Pick one model at the Translate model picker → every item runs on that model in a single queue. Pick several → the work is shared across them via a single shared queue. Multi-model is faster end-to-end (parallelism) but spreads cost across the chosen set. The L1 drill-in shows per-model rows so you can see who's doing what."),
            HelpCard("Speed / Mixed / Cost mode", "On the Translation L1 screen a three-way toggle controls how much the cheaper models dominate the queue. Cost (default) — aggressive bias, the cheapest model drains the queue first while expensive ones hesitate proportional to their price ratio (up to 2 min between pulls). Mixed — softened bias (cap 5 s). Speed — no bias, every model pulls as fast as its per-host caps allow. Switchable mid-run; the worker re-reads on every pull so the change takes effect within ~1 s. See Help - How it works for the exact hesitation formula."),
            HelpCard("Mode persistence", "Your Speed / Mixed / Cost pick is saved per-runId in SharedPreferences (TranslationModeStore). A process kill / app restart resumes the run in the same mode. Deleting the run clears the entry so prefs don't leak."),
            HelpCard("Restart failed", "When a multi-model run has errored rows, Restart failed reassigns each one to a different model than the one that failed — round-robin over the remaining models. On a single-model run, the row retries on the same model (no alternatives). Benched rows (rate-limit cooldown) auto-recover when the cooldown lifts and don't need a manual Restart."),
            HelpCard("Self-healing background", "Translation runs that get interrupted by an app restart, a coroutine cancellation, or a mid-flight kill are recovered by two coordinated paths: a 10-second sanity poll on the result page (catches stalled rows where done == total but !isFinished) and a 30-second app-wide background sweep across reports modified in the last 7 days (catches stalled rows in reports you haven't opened recently). Either path auto-reconciles the state and re-dispatches placeholders — see Help - How it works."),
            HelpCard("Cross-translate after a fan-out", "When a fan-out adds new meta rows after a translation has already run, the existing translation run automatically dispatches translations for the new rows too (addCrossTranslationItems). You don't need to re-launch the translation; the new content surfaces in the existing language picker."),
            HelpCard("Cost notes", "Translation is per-row: 1 Report with 5 agents + 3 meta results = 9 source items × N languages × M models worth of API calls. Use the Translate confirm dialog's count preview to avoid surprises. Mix cheap models with Cost-mode to keep total spend low; the bias means the expensive ones barely fire."),
            HelpCard("Limitations", "(1) Rerank tables aren't translated (they're structured ranks, not prose). (2) JSON traces aren't translated. (3) Source-content updates after a translation are not auto-retranslated — restart the translation. (4) Translations don't carry their own cost-override store; they use the same pricing as any other call.")
        )
    ),
)
